### ISSUE TITLE
Having multiple server.urls in project.json crashes Kestrel

### ISSUE THREAD

**Issue by sunsided** [aspnet/KestrelHttpServer#211]
Migrated from aspnet-contrib/AspNet.Security.OpenIdConnect.Server#135: When attempting to start a site with kestrel in the `microsoft/aspnet` beta 7 docker image (or my own `sunside/aspnet:1.0.0-beta8-15618` image), the application dies with a NullReferenceException, **if** I use more than one `server.url` in `project.json`.

That is

```json
"commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server=Microsoft.AspNet.Server.Kestrel --server.urls=http://auth:54540;http://resource:54540",
    "web": "Microsoft.AspNet.Hosting --server=Microsoft.AspNet.Server.WebListener --server.urls=http://auth:54540;http://resource:54540"
  },
```

works with `dnx web` on Windows but fails with `dnx kestrel` on Linux, whereas 

```json
"commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server=Microsoft.AspNet.Server.Kestrel --server.urls=http://auth:54540",
  },
```

works just fine.

Here's the output in all its glory:

```
markus@northbridge:docker/vnext-oauth-something$ docker run --rm -it vnextoauthsomething_server                                                                                                                                (09-18 21:40)
info    : [Microsoft.Framework.DependencyInjection.DataProtectionServices] User profile is available. Using '/root/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info    : [WebApplication1.Providers.AuthorizationProvider] In Created Authorization Provider
info    : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] Creating key {a4aad44a-1997-4bb0-9a83-071d14822f3e} with creation date 2015-09-18 19:40:41Z, activation date 2015-09-18 19:40:41Z, and expiration date 2015-12-17 19:40:41Z.
warning : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] No XML encryptor configured. Key {a4aad44a-1997-4bb0-9a83-071d14822f3e} may be persisted to storage in unencrypted form.
info    : [Microsoft.AspNet.DataProtection.Repositories.FileSystemXmlRepository] Writing data to file '/root/.local/share/ASP.NET/DataProtection-Keys/key-a4aad44a-1997-4bb0-9a83-071d14822f3e.xml'.
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.Server.Kestrel.Http.Listener+<>c__DisplayClass10_0.<Dispose>b__0 (System.Object _) [0x00000] in <filename unknown>:0
markus@northbridge:docker/vnext-oauth-something$                                                                                                                                                                               (09-18 21:40)
```

From experiments I know that `ConfigureServices` and `Configure` are executed, and then the app dies. I am *not* using the Core runtime here, just plain old mono. 

```
markus@northbridge:docker/vnext-oauth-something$ docker run --rm -it vnextoauthsomething_server bash                                                                                                                           (09-18 21:40)
root@2b04b09699b6:/app/src/WebApplication1# dnvm version
1.0.0-beta8-15516
root@2b04b09699b6:/app/src/WebApplication1# dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-beta8-15618
 Type:         Mono
 Architecture: x64
 OS Name:      Linux
 Runtime Id:   linux-x64
```

Full `project.lock.json` [in this gist](https://gist.github.com/sunsided/5b6c0d49ccd398a4d212) in case it matters.

**Comment by halter73** [comment]
I verified that multiple semicolon separated `server.urls` works when I modify the Kestrel sample project. I'll try to get back to this later to figure out how to repro this issue.

Unfortunately the NullReferenceException in Listener.Dispose is hiding the original error. This shouldn't be a problem with the latest Kestrel builds (-beta8-15628 and later) which have [the fix](https://github.com/aspnet/KestrelHttpServer/commit/47323a88e1c58f7e57c6f8c641415b2a992d22aa) for the Listener.Dispose bug.

@sunsided Your project.lock.json shows you are using Kestrel build beta8-15622. Can you try a later build and show us the new stack trace? You might have to switch your nuget feed from https://www.myget.org/F/aspnetvnext/ to https://www.myget.org/F/aspnetlitedev/

**Comment by sunsided** [comment]
Working on it. Using the same image mentioned above ([this Dockerfile](https://github.com/sunsided/aspnet-docker-beta8/blob/master/Dockerfile)), I replaced the feed in the `NuGet.Config`. Sadly the `dnu restore` then fails with

```
Errors in /app/src/ClientApplication/project.json
    Unable to locate Microsoft.IdentityModel.Protocols.OpenIdConnect >= 2.0.0-beta7-209170021
```

despite the dependency being marked as

```
 "Microsoft.AspNet.Authentication.OpenIdConnect": "1.0.0-*",
```

in the `project.json`. 

I'll see if I can get it to work.

**Comment by sunsided** [comment]
Okay, got it. The hidden error is a bit anticlimactic: It's an "address already in use" problem.

```
sunside@sagittaria:aspnet/vnext-oauth-something$ docker run --rm -it -p 54540:54540 vnextoauthsomething_server bash    (09-19 02:30)
root@9557b14b32be:/app/src/WebApplication1# dnx kestrel
info    : [Microsoft.Framework.DependencyInjection.DataProtectionServices] User profile is available. Using '/root/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info    : [WebApplication1.Providers.AuthorizationProvider] In Created Authorization Provider
info    : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] Creating key {64234e9f-46dd-442c-bf29-bc92c8fadefc} with creation date 2015-09-19 00:33:28Z, activation date 2015-09-19 00:33:28Z, and expiration date 2015-12-18 00:33:28Z.
warning : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] No XML encryptor configured. Key {64234e9f-46dd-442c-bf29-bc92c8fadefc} may be persisted to storage in unencrypted form.
info    : [Microsoft.AspNet.DataProtection.Repositories.FileSystemXmlRepository] Writing data to file '/root/.local/share/ASP.NET/DataProtection-Keys/key-64234e9f-46dd-442c-bf29-bc92c8fadefc.xml'.
Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -98 EADDRINUSE address already in use
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check (Int32 statusCode) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.listen (Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle handle, Int32 backlog, Microsoft.AspNet.Server.Kestrel.Networking.uv_connection_cb cb) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.Listen (Int32 backlog, System.Action`4 callback, System.Object state) [0x00000] in <filename unknown>:0
root@9557b14b32be:/app/src/WebApplication1#
```

No problem with a single address.

**Comment by halter73** [comment]
It's really bad getting a NullReferenceException because an address is already in use, but at least it's fixed in the latest builds.

I think the error is reasonably clear now so I'm closing this issue.

**Comment by sunsided** [comment]
Well, technically the problem persists. :grin: 

Why am I allowed to set multiple URLs to a `--server.urls=` parameter when only (and exactly) one URL is actually expected? Shouldn't the Kestrel behavior be the same as with HttpListener?

**Comment by Tratcher** [comment]
You need to have unique ports. Kestrel is listening on raw sockets, it doesn't dispatch on host name.

**Comment by sunsided** [comment]
I understand, but in that case the URL list should probably be checked before attempting to use the the same port twice.

**Comment by Tratcher** [comment]
And throw, or just filter it out?

**Comment by sunsided** [comment]
It should probably be silently ignoring multiple occurrences, but whatever works best, really. :grin: 

I don't know enough about the internals to give a better answer, I just never saw Apache or nginx spit exceptions at me when I configured it wrong. It's also not super obvious that it is the app *itself* that already uses the address when it is just starting up.
*We* know that now, but if I had given the code to my colleagues they would have tried to find that rogue unix process with cryptic unix magic („wait, I already started it before?“), because the very same configuration works on both other hosts, IIS and HttpListener.

My point is that I (as a user) *do* want to see that something didn't work as expected, I just don't want it to be served with a stack trace (especially if it's somewhat generic).  That's like Word exploding if the file is write protected.

At the very least there should be a good error message explaining the double port situation instead of an exception. If kestrel goes down after that, that's fine with me - others do that as well.
