### ISSUE TITLE
Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#2271]
`dotnet new web`

Switch from `Microsoft.AspNetCore.All` to `Microsoft.AspNetCore.App`.

`dotnet restore`

`dotnet run`

```
C:\Users\daroth\Desktop\test2>dotnet run
Using launch settings from C:\Users\daroth\Desktop\test2\Properties\launchSettings.json...
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:44321 on the IPv4 loopback interface: 'Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to https://localhost:44321 on the IPv6 loopback interface: 'Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://localhost:44321. ---> System.AggregateException: One or more errors occurred. (Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.) (Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.) ---> System.TypeLoadException: Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at System.Buffers.MemoryPool..ctor()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread..ctor(LibuvTransport transport)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.<BindAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__22`1.MoveNext()

Unhandled Exception: System.IO.IOException: Failed to bind to address https://localhost:44321. ---> System.AggregateException: One or more errors occurred. (Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.) (Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.) ---> System.TypeLoadException: Method 'Pin' in type 'System.Buffers.MemoryPoolBlock' from assembly 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at System.Buffers.MemoryPool..ctor()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread..ctor(LibuvTransport transport)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.<BindAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__22`1.MoveNext()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at test2.Program.Main(String[] args) in C:\Users\daroth\Desktop\test2\Program.cs:line 17

C:\Users\daroth\Desktop\test2>dotnet --info
.NET Command Line Tools (2.1.300-preview2-008017)

Product Information:
 Version:            2.1.300-preview2-008017
 Commit SHA-1 hash:  f4a0d2db0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008017\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26123-02
  Build    : b64cb46124df1f7e64d7b7cde1034f693b270ceb
```

**Comment by muratg** [comment]
@pakrym could you investigate? 

cc @JunTaoLuo could be related to Shared Runtime work.

cc @halter73 @Tratcher FYI.

**Comment by pakrym** [comment]
PCP build only. Breaking change in corefx that corefxlab and we have to react to.

**Comment by Eilon** [comment]
We're still waiting for a new build for this?

**Comment by pakrym** [comment]
No, release/2.1 is fixed, I'm merging/updating version in dev now.

**Comment by Eilon** [comment]
Great!

**Comment by pakrym** [comment]
Fixed both in dev and release, as far as I know, there was not PCP build that includes this change yet.

**Comment by natemcmaster** [comment]
The fix is available in 2.1.0-preview1-28226. https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1#product-build-cli-build-20180202-02-1347550

**Comment by muratg** [comment]
@natemcmaster @pakrym CTI folks tested the build, and they're claiming it's not fixed in this build. Could you guys take a look please?

**Comment by muratg** [comment]
cc @balachir

**Comment by natemcmaster** [comment]
Where can we find details of CTI's repro steps? This fix requires aspnetcore 2.1.0-preview1-28226 or newer.

**Comment by DamianEdwards** [comment]
According to the notes I saw they're using the ProdCon build that contains 2.1.0-preview1-28226 of ASP.NET Core (judging by the version I see on my machine with the same build).

**Comment by davidfowl** [comment]
It's fixed.

**Comment by muratg** [comment]
CLI used: Build 20180202-02 CLI version   2.1.300-preview1-008019

The claim is that restore fails on Ubuntu 16.04.  (It's possible that it's a user error on CTI's part, but we should verify.)

**Comment by pakrym** [comment]
`restore fails on Ubuntu` this bug is a runtime exception.

**Comment by muratg** [comment]
Yeah, what they're hitting right now seems to be the LZMA issue: https://github.com/aspnet/Universe/issues/848.  👍
