### ISSUE TITLE
Handle is invalid

### ISSUE THREAD

**Issue by aluitink** [aspnet/KestrelHttpServer#262]
Hello,
I'm testing the WebSocketMiddleware and after rapidly opening and closing about 20 - 30 websocket connections in a serial manner I receive the following error:

![image](https://cloud.githubusercontent.com/assets/3255752/10515803/c289bf0c-731a-11e5-9aba-119dc3019772.png)

Setup:
app.UseWebSockets(new WebSocketOptions() { ReplaceFeature = true });

It took awhile but the socket seems to open and close gracefully now, but after a while I get the above exception.

The route creates a number of tasks that may or may not be finished by the time the socket goes out of scope, but the socket itself is not used in those tasks.

Anyone have any thoughts?

**Comment by halter73** [comment]
Do you see this issue in beta 8? This issue seems very similar to https://github.com/aspnet/KestrelHttpServer/issues/202 which was fixed.

**Comment by habathcx** [comment]
Nope beta 6 .. sorry I did not find when I searched, I'll try 8. Thanks!

**Comment by muratg** [comment]
@aluitink Still an issue for you?  If so, please file another bug or reactivate this one.  Thanks.

**Comment by aluitink** [comment]
Looks good in 8 and RC1

**Comment by muratg** [comment]
Awesome, thanks!
