### ISSUE TITLE
NullReferenceException when running Kestrel against vNext project on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by jamesseanwright** [aspnet/KestrelHttpServer#52]
When attempting to launch a vNext site with Kestrel on Ubuntu 14.04 LTS, I receive a  `NullReferenceException`:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.loop_size () [0x00000] in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNet.Server.Kestrel.Networking.Libuv uv) [0x00000] in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) [0x00000] in <filename unknown>:0 
```

In the *project.json* file for both projects, Kestrel is launched with the following command:
```
Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004
```
This occurs with my own codebase and the *HelloMvc* example in the *Home* repository. Is this a known issue that is resolvable?

Cheers!
James

**Comment by Tragetaschen** [comment]
It's [known and already better](https://github.com/aspnet/KestrelHttpServer/issues/41). You need to insall libuv 1.*

**Comment by Praburaj** [comment]
This is fixed now in `RC1`. With latest `dev` bits it is expected to throw a more descriptive error message as in this commit https://github.com/aspnet/KestrelHttpServer/pull/48/files. If you are on master its going to take a while to get the fix merged to master. But installing `libuv` should solve the issue for you.

**Comment by jamesseanwright** [comment]
I've installed libuv but to no avail unfortunately. I can confirm that it's installed in the `/usr/local/lib` directory:
```
james@james-ubuntu:~/dev/dotnet/vNext/samples/HelloWeb$ ls /usr/local/lib/
libuv.a   libuv.so    libuv.so.1.0.0  python2.7
libuv.la  libuv.so.1  pkgconfig       python3.4
```

However, I'm still receiving the same exception. Interestingly, looking at the `Microsoft.AspNet.Server.Kestrel.KestrelEngine class` (line 58) demonstrates how it determines libuv's location:
```
                [...]
                else
                {
                    libraryPath = "libuv.so.1";
                }
            }
            Libuv.Load(libraryPath);
```

Is it installed in the correct location or am I being silly?

**Comment by jamesseanwright** [comment]
OK, turns out it wasn't a location issue. I had to run `ldconfig` to refresh the shared library cache. Works like a charm! Thanks for your prompt responses.

**Comment by Praburaj** [comment]
Good to know it worked :)
